### ISSUE TITLE
Set up CLA assistant

### ISSUE THREAD

**Issue by FiniteReality** [novelrt/Fabulist#2]
I assume the CLA stuff needs to be turned on per-repo. Until then, no pull requests will be accepted.

cc @RubyNova since I don't know how to do this :sweat_smile:

**Comment by RubyNova** [comment]
It's organisation wide.

It should already be working.

**Comment by FiniteReality** [comment]
In that case, I'll close this after I confirm that it works

**Comment by RubyNova** [comment]
Just double checked - CLA Assistant says none of the repositories have been excluded. This should just work.

**Comment by FiniteReality** [comment]
Confirmed to be working in #4
