### ISSUE TITLE
Use something other than getopt on windows

### ISSUE THREAD

**Issue by FiniteReality** [novelrt/Fabulist#6]
Alternatively: drop getopt entirely in favour of something else.

Currently windows builds are failing due to the CLI applications requiring getopt, which is POSIX/GNU-specific. To resolve this, we should write our own argument parsing on Windows.

If we decide to keep getopt, we probably should prefer it if it's available, using CheckCXXSourceCompiles.

**Comment by RubyNova** [comment]
Looks to be pretty small but an initial search on conan gave me https://conan.io/center/args-parser

**Comment by FiniteReality** [comment]
I wrote a custom args parser to fix this. We don't test against Windows systems with getopt available, so I have no idea if it'll break.
